### ISSUE TITLE
Currently does not work in Unity 2018.3.0f2

### ISSUE THREAD

**Issue by GithubPrankster** [Seanba/Aseprite2Unity#1]
I put the unity package on my project, but it did nothing to the aseprite files I tried putting on, and also the editor itself seems to report issues inside the scripts. (note I also had the supertiled2unity package in just in case that does something)

**Comment by Seanba** [comment]
Hi there, @GithubPrankster. I use both ST2U and A2U without error. Can you give me detailed information on the reported issues from the editor? Thanks.

**Comment by GithubPrankster** [comment]
Sorry for making you wait, I got much less time to use my stuff today. Anyways, I went and tracked down the errors from the editor,
(currently had to uncheck the test files that the package comes with else it wouldn't give me the errors)

- Currently, it seems that expression bodied members are part of a specification outside of C# 4.0 (current one being used by me), this means that possibly i'm running a version lower than the one A2U requires, but I can't tell.
![2019-01-14_22-41-05](https://user-images.githubusercontent.com/33995085/51150453-8423d500-184d-11e9-8e5d-7966f3d08e82.png)

> These are the error messages I got.

**Comment by Seanba-ohtm** [comment]
Hi again, @GithubPrankster.  `.NET 3.5` is now deprecated with Unity 2018.3. You will need to go into your `Project Settings` for `Player` and set the `Scripting Runtime Version` to `.NET 4.x Equivalent`.

![image](https://user-images.githubusercontent.com/46612918/51150753-6fcfe000-182d-11e9-9186-153f95211820.png)

**Comment by Seanba** [comment]
BTW, did you update an old project to Unity 2018.3? I'm just wondering how you got your Scripting Runtime to an unsupported version. Thanks!

**Comment by GithubPrankster** [comment]
Yes, I did update a project from 2018.2 to 2018.3, might be why the issue happened. I'd say it would be good if you put a disclaimer about updating projects to 2018.3 and forgetting the new runtime. Anyways, thanks for solving my issue, have a great day!
