### ISSUE TITLE
A2U cannot read aseprite files correctly

### ISSUE THREAD

**Issue by GithubPrankster** [Seanba/Aseprite2Unity#2]
Unable to tell why. Here are the errors I got:
![2019-01-14_23-50-03](https://user-images.githubusercontent.com/33995085/51153418-3e6c0a00-1857-11e9-89db-73b2dc15bf9e.png)
I put the most current version, 1.0.3.

**Comment by GithubPrankster** [comment]
Also I updated my project to the right runtime.

**Comment by cosmosgc** [comment]
Same here

**Comment by cosmosgc** [comment]
![image](https://user-images.githubusercontent.com/8571009/51183080-5a06fd00-18b7-11e9-8f56-7458727a6593.png)
type: F1FA show the same error, same lines

But yeah, you can have the aseprite file.


[hope.zip](https://github.com/Seanba/Aseprite2Unity/files/2759803/hope.zip)

**Comment by GithubPrankster** [comment]
Note that all aseprite objects I attempted to use give the error

**Comment by Seanba** [comment]
Hi again. According to the Aseprite dev the color profile chunk [is a beta feature](https://github.com/aseprite/aseprite/issues/1951). Is there a reason you are using a beta version of Aseprite instead of the latest release version?

I'll keep this bug up but, in general, I don't support support features in the beta stage as the developer is likely to change/drop such support.

**Comment by GithubPrankster** [comment]
I'm using the current beta of aseprite, yes, so it might be why.

**Comment by seanb-22ct** [comment]
The beta version did uncover a bug however. I should be handling unsupported chunk types without crashing the importer. I'll put a fix for that something this weekend probably but in the meantime if you use the release version of Aseprite you should be fine. Thanks for the bug report.

**Comment by Seanba** [comment]
I pushed a new version of Aseprite2Unity that should help with the beta version. Color profiles will not be fully supported but it at least won't crash the importer.

https://seanba.itch.io/aseprite2unity/devlog/63956/aseprite2unity-version-104

**Comment by GithubPrankster** [comment]
Thanks, hopefully it works!
